server:
  port: 8080

# dataSource数据源
spring:
  datasource:
    #jdbc配置
    driverClass: com.mysql.cj.jdbc.Driver #数据库驱动类
    user: root        #数据库用户名
    password: root    #数据库用户密码
    jdbcUrl: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC  #数据库连接URL
    #c3cp0连接池
    type: com.mchange.v2.c3p0.ComboPooledDataSource  #指定自定义连接池类型，不指定则默认使用hikari
    dataSourceName: dataSource
    initialPoolSize: 1  #连接池初始化连接数
    minPoolSize: 1       #连接池最小连接数
    maxPoolSize: 20      #连接池最大连接数
    autoCommitOnClose: false  #关闭连接后不自动提交
    checkoutTimeout: 10000    #连接超时时间
    maxIdleTime: 1800000      #连接的最大空闲时间，超过这个时间，某个数据库连接还没有被使用，则会断开掉这个连接
    acquireRetryAttempts: 2   #连接池在获取连接失败后允许重试次数
