package com.qingchen.apicore.model;

import java.io.Serializable;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table t_users
 */
public class Tusers implements Serializable {
    /**
     * Database Column Remarks:
     *   用户id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     * Database Column Remarks:
     *   用户名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.username
     *
     * @mbg.generated
     */
    private String username;

    /**
     * Database Column Remarks:
     *   密码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.password
     *
     * @mbg.generated
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.email
     *
     * @mbg.generated
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.homeUrl
     *
     * @mbg.generated
     */
    private String homeurl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.screenName
     *
     * @mbg.generated
     */
    private String screenname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.created
     *
     * @mbg.generated
     */
    private Integer created;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.activated
     *
     * @mbg.generated
     */
    private Integer activated;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.logged
     *
     * @mbg.generated
     */
    private Integer logged;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_users.groupName
     *
     * @mbg.generated
     */
    private String groupname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_users
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.uid
     *
     * @return the value of t_users.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.uid
     *
     * @param uid the value for t_users.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.username
     *
     * @return the value of t_users.username
     *
     * @mbg.generated
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.username
     *
     * @param username the value for t_users.username
     *
     * @mbg.generated
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.password
     *
     * @return the value of t_users.password
     *
     * @mbg.generated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.password
     *
     * @param password the value for t_users.password
     *
     * @mbg.generated
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.email
     *
     * @return the value of t_users.email
     *
     * @mbg.generated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.email
     *
     * @param email the value for t_users.email
     *
     * @mbg.generated
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.homeUrl
     *
     * @return the value of t_users.homeUrl
     *
     * @mbg.generated
     */
    public String getHomeurl() {
        return homeurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.homeUrl
     *
     * @param homeurl the value for t_users.homeUrl
     *
     * @mbg.generated
     */
    public void setHomeurl(String homeurl) {
        this.homeurl = homeurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.screenName
     *
     * @return the value of t_users.screenName
     *
     * @mbg.generated
     */
    public String getScreenname() {
        return screenname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.screenName
     *
     * @param screenname the value for t_users.screenName
     *
     * @mbg.generated
     */
    public void setScreenname(String screenname) {
        this.screenname = screenname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.created
     *
     * @return the value of t_users.created
     *
     * @mbg.generated
     */
    public Integer getCreated() {
        return created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.created
     *
     * @param created the value for t_users.created
     *
     * @mbg.generated
     */
    public void setCreated(Integer created) {
        this.created = created;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.activated
     *
     * @return the value of t_users.activated
     *
     * @mbg.generated
     */
    public Integer getActivated() {
        return activated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.activated
     *
     * @param activated the value for t_users.activated
     *
     * @mbg.generated
     */
    public void setActivated(Integer activated) {
        this.activated = activated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.logged
     *
     * @return the value of t_users.logged
     *
     * @mbg.generated
     */
    public Integer getLogged() {
        return logged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.logged
     *
     * @param logged the value for t_users.logged
     *
     * @mbg.generated
     */
    public void setLogged(Integer logged) {
        this.logged = logged;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_users.groupName
     *
     * @return the value of t_users.groupName
     *
     * @mbg.generated
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_users.groupName
     *
     * @param groupname the value for t_users.groupName
     *
     * @mbg.generated
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }
}